package com.elvaco.mvp.core.domainmodels;

public enum MeterDefinitionType {
  UNKNOWN_METER_TYPE,
  HOT_WATER_METER_TYPE,
  DISTRICT_HEATING_METER_TYPE,
  DISTRICT_COOLING_METER_TYPE,
  GAS_METER_TYPE,
  WATER_METER_TYPE,
  COLD_WATER_METER_TYPE,
}
