image: sgrio/java-oracle:jdk_8

stages:
    - build
    - test

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches
build:
    stage: build
    script:
        - ./gradlew assemble

test:
    stage: test
    script:
        - ./gradlew check
