# === Global ===
image:
  name: gradle:jdk11

stages:
  - docker
  - prepare
  - build
  - pre-test
  - test
  - deploy-staging
  - post-staging
  - deploy-prod
  - post-prod
  - finalize

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
  SALTAPI_URL: "https://salt.elvaco.se:8000"
  SALTAPI_EAUTH: "pam"
  SALTAPI_USER: "saltapi"
  SALTAPI_PASS: "8J^SQvg&zR%rTd5YNuw"
  GITLAB_API_TOKEN: "J1Jb27mvUxZqAVx5MhhJ"
  DOCKER_REGISTRY_HOST: gitlab.elvaco.se:4567
  DOCKER_REGISTRY_URL: gitlab.elvaco.se:4567/elvaco/mvp

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export YARN_CACHE_FOLDER=`pwd`/.yarn

# === Templates ===
.no_cache:
  cache: {}

.cache_gradle:
  cache:
    key: "$CI_COMMIT_REF_NAME-gradle"
    paths:
      - .gradle/
      - .yarn
      - frontend/node_modules

.cache_gradle_read_only:
  extends: .cache_gradle
  cache:
    policy: pull

.auto_deploy:
  extends: .no_cache
  image: $DOCKER_REGISTRY_URL/ci-utils:latest

.acceptance_test:
  extends: .cache_gradle_read_only
  services:
    - name: selenium/standalone-chrome
      alias: selenium_chrome_container_url
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-cucumber"
    when: always
    paths:
      - acceptance_tests/target/cucumber
    expire_in: 2 days
  script:
    - gradle cucumber '-Pno-docker'

# === Jobs ===
docker:postgresql:
  extends: .no_cache
  stage: docker
  dependencies: []
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker build -t $DOCKER_REGISTRY_URL/postgresql:latest -f docker/Dockerfile-postgresql .
    - docker push $DOCKER_REGISTRY_URL/postgresql:latest

docker:test-upgrade:
  extends: .no_cache
  stage: docker
  dependencies: []
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker build -t $DOCKER_REGISTRY_URL/test-upgrade:latest -f docker/Dockerfile-test-upgrade .
    - docker push $DOCKER_REGISTRY_URL/test-upgrade:latest

docker:acceptance-test:
  extends: .no_cache
  stage: docker
  dependencies: []
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker build -t $DOCKER_REGISTRY_URL/acceptance-test:latest -f docker/Dockerfile-acceptance-test .
    - docker push $DOCKER_REGISTRY_URL/acceptance-test:latest

docker:ci-utils:
  extends: .no_cache
  stage: docker
  dependencies: []
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker build -t $DOCKER_REGISTRY_URL/ci-utils:latest -f docker/Dockerfile-ci-utils .
    - docker push $DOCKER_REGISTRY_URL/ci-utils:latest

docker:gradle-jdk:
  extends: .no_cache
  stage: docker
  dependencies: []
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker build -t $DOCKER_REGISTRY_URL/gradle-jdk11:latest -f docker/Dockerfile-gradle-jdk11 .
    - docker push $DOCKER_REGISTRY_URL/gradle-jdk11:latest

prepare:gradle-clean:
  extends: .cache_gradle
  stage: prepare
  dependencies: []
  script:
    - gradle clean
  only:
    - schedules
    - master
    - develop
    - tags

prepare:version:
  extends: .no_cache
  stage: prepare
  dependencies: []
  image:
    name: alpine/git:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - git describe --tags --abbrev=7 --dirty > .version
    - chmod 644 .version
  artifacts:
    paths:
      - .version
    expire_in: 7 days

prepare:update-salt:
  extends: .no_cache
  image: $DOCKER_REGISTRY_URL/ci-utils:latest
  dependencies: []
  stage: prepare
  only:
    - schedules
    - tags
  script:
    - pepper --fail-any -G 'roles:salt-master' event.fire_master update salt/fileserver/gitfs/update

build:
  extends: .cache_gradle
  image: $DOCKER_REGISTRY_URL/gradle-jdk11:latest
  stage: build
  services:
    - name: $DOCKER_REGISTRY_URL/postgresql:latest
      alias: pg_host
  dependencies:
    - prepare:version
  script:
    - gradle classes checkstyle spotbugs test assemble -PisCI
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:7}"
    paths:
      - backend/configuration/build/distributions/
      - backend/geoservice/build/distributions/
      - .version
      - backend/*/build/libs
      - backend/*/build/classes
      - backend/*/build/generated
      - acceptance_tests/build/libs/*.jar
      - acceptance_tests/build/classes/*


pre-test:docker-mvp-app:
  extends: .no_cache
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY_URL/mvp:${CI_COMMIT_REF_NAME}
    APM_VERSION: 1.1.0
    APM_SERVER: swarm-worker-01.elvaco.se:8200
  stage: pre-test
  dependencies:
    - build
    - prepare:version
  tags:
    - shell
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export DOCKER_IMAGE_NAME="$DOCKER_REGISTRY_URL/mvp:${CI_COMMIT_SHA}"
  script:
    - cat .version
    - git describe --tags --abbrev=7
    - docker build --build-arg APM_VERSION=$APM_VERSION --build-arg APM_SERVER=$APM_SERVER --build-arg MVP_APPVER=$(cat ./.version) -t ${DOCKER_IMAGE_NAME} -f docker/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker push ${DOCKER_IMAGE_NAME}

pre-test:docker-geoservice-app:
  extends: .no_cache
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY_URL/geoservice:${CI_COMMIT_REF_NAME}
    APM_VERSION: 1.1.0
    APM_SERVER: swarm-worker-01.elvaco.se:8200
  stage: pre-test
  dependencies:
    - build
    - prepare:version
  tags:
    - shell
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export DOCKER_IMAGE_NAME="$DOCKER_REGISTRY_URL/geoservice:${CI_COMMIT_SHA}"
  script:
    - cat .version
    - git describe --tags --abbrev=7
    - docker build --build-arg APM_VERSION=$APM_VERSION --build-arg APM_SERVER=$APM_SERVER --build-arg GEOSERVICE_APPVER=$(cat ./.version) -t ${DOCKER_IMAGE_NAME} -f docker/Dockerfile-geoservice .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
    - docker push ${DOCKER_IMAGE_NAME}

test:karate:
  image: $DOCKER_REGISTRY_URL/acceptance-test:latest
  stage: test
  services:
    - name: docker:dind
      alias: docker-host
  dependencies:
    - build
  after_script:
    - docker-compose down -v
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export MVP_TAG="${CI_COMMIT_SHA}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
  script:
    - docker-compose up -d application postgresql
    - source ./scripts/docker-check-startup && check_application_startup application
    - ./gradlew -Dkarate.api.endpoint=http://docker-host:8080 karate
  artifacts:
    paths:
      - backend/karate_tests/target/karate.log
    expire_in: 3 days

test:acceptance:
  image: $DOCKER_REGISTRY_URL/acceptance-test:latest
  stage: test
  dependencies:
    - build
  after_script:
    - docker-compose down -v
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export MVP_TAG="${CI_COMMIT_SHA}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
  script:
    - docker-compose up -d application postgresql google-chrome
    - source ./scripts/docker-check-startup && check_application_startup application
    - docker ps -a
    - docker inspect mvp_google-chrome_1
    - ./gradlew -Pno-docker cucumber
  services:
    - name: docker:dind
      alias: docker-host
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-cucumber"
    when: always
    paths:
      - acceptance_tests/target/cucumber
    expire_in: 2 days
  variables:
    DOCKER_DRIVER: overlay2
    MVP_TAG: ${CI_COMMIT_REF_NAME}
    MVP_SERVER: "http://docker-host"
    MVP_WEB_SERVER: "http://application"
    CHROME_URL: "http://docker-host:5555/wd/hub"
    MVP_WEB_PORT: 8080

test:system:
  extends: .cache_gradle_read_only
  stage: test
  dependencies:
    - build
  services:
    - name: $DOCKER_REGISTRY_URL/postgresql:latest
      alias: pg_host
    - name: rabbitmq
      alias: rabbit_host
  script:
    - gradle -PisCI -x update -x generateProdJooqSchemaSource systemTest
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-system"
    when: on_failure
    paths:
      - backend/configuration/build/reports/tests/systemTestCI/*
    expire_in: 2 days

test:jira_script:
  extends: .no_cache
  image: frolvlad/alpine-python3
  stage: test
  dependencies: []
  before_script:
    - cd scripts/jira/
    - pip install -r requirements.txt
  script:
    - flake8
    - nose2 --with-coverage --verbose

test:upgrade:
  extends: .no_cache
  image: $DOCKER_REGISTRY_URL/test-upgrade:latest
  variables:
    DOCKER_DRIVER: overlay2
    MVP_UPGRADE_FROM_TAG: production
    MVP_UPGRADE_TO_TAG: ${CI_COMMIT_REF_NAME}
    TEST_HOST: docker-host
    APM_ENV: upgrade-test
  stage: test
  dependencies: []
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export MVP_UPGRADE_TO_TAG=${CI_COMMIT_SHA}
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
  after_script:
    - docker-compose down -v
  services:
    - name: docker:dind
      alias: docker-host
  script:
    - docker info
    - docker ps
    - ./scripts/upgrade-test.sh $MVP_UPGRADE_FROM_TAG $MVP_UPGRADE_TO_TAG $TEST_HOST $APM_ENV

deploy:staging:
  extends: .auto_deploy
  stage: deploy-staging
  dependencies:
    - prepare:version
  only:
    - schedules
    - tags
  variables:
    API_USER: "mvpadmin@elvaco.se"
    API_PASSWORD: "PmpQnaFaAFD0b867fyZoGFSyb32Z1BFr"
    API_URL: "https://evo-staging.elvaco.se"
  environment:
    name: evo-staging.elvaco.se
    url: https://evo-staging.elvaco.se
  before_script:
    - test "$CI_COMMIT_REF_NAME" != "develop" && export SALTENV="saltenv=\"$CI_COMMIT_REF_NAME\""
    - test "$CI_COMMIT_REF_NAME" != "develop" && export MVP_VERSION=$(cat .version)
    - test "$CI_COMMIT_REF_NAME" == "develop" && export MVP_VERSION=$CI_COMMIT_SHA
  script:
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-staging' state.apply mvp.db.system $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-staging' state.apply mvp.app.web $SALTENV
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-staging' state.apply mvp.db.geoservice.create $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-staging' state.apply mvp.app.geoservice.deploy $SALTENV pillar="{\"mvp_version\":\"$MVP_VERSION\"}"
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-staging' state.apply mvp.db.mvp.create $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-staging' state.apply mvp.app.mvp.deploy $SALTENV pillar="{\"mvp_version\":\"$MVP_VERSION\"}"
    - while [ 1 ]; do curl --fail --silent --user "$API_USER:$API_PASSWORD" "$API_URL/actuator/health" >/dev/null && exit 0; echo "Waiting for application to start"; sleep 1; done

post-staging:acceptance:
  extends: .acceptance_test
  stage: post-staging
  dependencies:
    - build
  only:
    - schedules
    - tags
  variables:
    CHROME_URL: "http://selenium_chrome_container_url:4444/wd/hub"
    MVP_SERVER: "https://evo-staging.elvaco.se"
    MVP_WEB_PORT: 443
    MVP_API_PORT: 443
    MVP_ADMIN_PASSWORD: PmpQnaFaAFD0b867fyZoGFSyb32Z1BFr

post-staging:performance:
  image: frolvlad/alpine-python3
  stage: post-staging
  only:
    - schedules
    - tags
  variables:
    MVP_URL: "https://evo-staging.elvaco.se"
    USER_EMAIL: performance@tester.se
    USER_PASSWORD: 'Ah@4wZEzdLexuFtqO9c2J!1gD8*JMtfJ7'
  before_script:
    - pip install -r scripts/performance/requirements.txt
  script:
    - python scripts/performance/time_requests.py

deploy:production:
  extends: .auto_deploy
  stage: deploy-prod
  dependencies:
    - prepare:version
  only:
    - schedules
    - tags
  when: manual
  allow_failure: false #block the pipeline from continuing until we've deployed to prod
  variables:
    API_USER: "mvpadmin@elvaco.se"
    API_PASSWORD: "PmpQnaFaAFD0b867fyZoGFSyb32Z1BFr"
    API_URL: "https://evo.elvaco.se"
  environment:
    name: evo.elvaco.se
    url: https://evo.elvaco.se
  before_script:
    - test "$CI_COMMIT_REF_NAME" != "develop" && export SALTENV="saltenv=\"$CI_COMMIT_REF_NAME\""
    - test "$CI_COMMIT_REF_NAME" != "develop" && export MVP_VERSION=$(cat .version)
    - test "$CI_COMMIT_REF_NAME" == "develop" && export MVP_VERSION=$CI_COMMIT_SHA
  script:
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-prod' state.apply mvp.db.system $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-prod' state.apply mvp.app.web $SALTENV
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-prod' state.apply mvp.db.geoservice.create $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-prod' state.apply mvp.app.geoservice.deploy $SALTENV pillar="{\"mvp_version\":\"$MVP_VERSION\"}"
    - pepper --fail-any -C 'G@roles:postgresql-server and G@env:mvp-prod' state.apply mvp.db.mvp.create $SALTENV
    - pepper --fail-any -C 'G@roles:mvp-app and G@env:mvp-prod' state.apply mvp.app.mvp.deploy $SALTENV pillar="{\"mvp_version\":\"$MVP_VERSION\"}"
    - while [ 1 ]; do curl --fail --silent --user "$API_USER:$API_PASSWORD" "$API_URL/actuator/health" >/dev/null && exit 0; echo "Waiting for application to start"; sleep 1; done

post-prod:acceptance:
  extends: .acceptance_test
  stage: post-prod
  dependencies:
    - build
  only:
    - schedules
    - tags
  variables:
    CHROME_URL: "http://selenium_chrome_container_url:4444/wd/hub"
    MVP_SERVER: "https://evo.elvaco.se"
    MVP_WEB_PORT: 443
    MVP_API_PORT: 443
    MVP_ADMIN_PASSWORD: PmpQnaFaAFD0b867fyZoGFSyb32Z1BFr

finalize:tag-production-mvp-docker:
  extends: .no_cache
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY_URL/mvp:${CI_COMMIT_REF_NAME}
  stage: finalize
  dependencies: []
  tags:
    - shell
  only:
    - schedules
    - tags
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export DOCKER_IMAGE_NAME="$DOCKER_REGISTRY_URL/mvp:${CI_COMMIT_SHA}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
  script:
    - docker pull ${DOCKER_IMAGE_NAME}
    - docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_REGISTRY_URL}/mvp:production
    - docker push ${DOCKER_REGISTRY_URL}/mvp:production

finalize:tag-production-geoservice-docker:
  extends: .no_cache
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_REGISTRY_URL/geoservice:${CI_COMMIT_REF_NAME}
  stage: finalize
  dependencies: []
  tags:
    - shell
  only:
    - schedules
    - tags
  before_script:
    - test "$CI_COMMIT_REF_NAME" == "develop" && export DOCKER_IMAGE_NAME="$DOCKER_REGISTRY_URL/geoservice:${CI_COMMIT_SHA}"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY_HOST
  script:
    - docker pull ${DOCKER_IMAGE_NAME}
    - docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_REGISTRY_URL}/geoservice:production
    - docker push ${DOCKER_REGISTRY_URL}/geoservice:production

finalize:create-jira-version:
  extends: .no_cache
  image: frolvlad/alpine-python3
  dependencies:
    - prepare:version
  stage: finalize
  only:
    - schedules
    - tags
  allow_failure: true
  variables:
    JIRA_USER: "app.jira.evo@elvaco.se"
    JIRA_TOKEN: "xR5ABiHwbEWrOiEY71BW9E99"
  before_script:
    - pip install -r scripts/jira/requirements.txt
  script:
    - python3 scripts/jira/fixversion.py --version $(cat .version) --jira_user $JIRA_USER --jira_token $JIRA_TOKEN
