version: "2.1"
services:
  application:
    environment:
      MVP_OPTS: -Dspring.profiles.active=postgresql
    build:
      context: .
      args:
        MVP_APPVER: ${MVP_APPVER:-unknown-version}
    ports:
      - "80"
    links:
      - postgresql
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    environment:
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432:5432}"
  geoservice-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: geoservice
      POSTGRES_PASSWORD: geoservice
    ports:
      - "${DOCKER_GEOSERVICE_DB_PORT:-5432:5432}"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
