version: "2.1"
services:
  application:
    environment:
      MVP_OPTS: -Dspring.profiles.active=compose
    build:
      context: .
      args:
        MVP_APPVER: ${MVP_APPVER:-unknown-version}
    ports:
      - "80"
    links:
      - postgresql
  postgresql:
    build:
      context: docker
    image: postgres:9.6
    environment:
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}"
