version: "2.1"
services:
  application:
    environment:
      MVP_OPTS: -Dspring.profiles.active=compose
    build:
      context: .
      args:
        MVP_APPVER: ${MVP_APPVER:-unknown-version}
    ports:
      - "80"
    links:
      - postgresql
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
    environment:
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432:5432}"
  rabbitmq:
      image: rabbitmq:management
      ports:
          - "8090:15672"
          - "5672:5672"
