version: "2.1"
services:
  application:
    image: "gitlab.elvaco.se:4567/elvaco/mvp/mvp:${MVP_TAG:-production}"
    environment:
      MVP_OPTS: -Dspring.profiles.active=postgresql -Dliquibase.url=jdbc:postgresql://postgresql:5432/mvp -Dspring.datasource.url=jdbc:postgresql://postgresql:5432/mvp -Dspring.rabbitmq.host=rabbitmq -Dspring.rabbitmq.username=guest -Dspring.rabbitmq.password=guest
    ports:
      - "8080:80"
    links:
      - postgresql
  postgresql:
    image: gitlab.elvaco.se:4567/elvaco/mvp/postgresql:latest
    environment:
      POSTGRES_USER: mvp
      POSTGRES_PASSWORD: mvp
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432:5432}"
  geoservice-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: geoservice
      POSTGRES_PASSWORD: geoservice
    ports:
      - "${DOCKER_GEOSERVICE_DB_PORT:-5432:5432}"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
  google-chrome:
    image: selenium/standalone-chrome
    ports:
      - "5555:4444"
