export const enum EndPoints {
  addresses = '/selections/addresses',
  cities = '/selections/cities',
  facilities = '/selections/facilities',
  gatewaySerials = '/selections/gateway-serials',
  gatewayStatuses = '/selections/gateway-statuses',
  meterStatuses = '/selections/meter-statuses',
  media = '/selections/media',
  secondaryAddresses = '/selections/secondary-addresses',
  selectionTree = '/selection-tree',
  meters = '/meters',
  meterMapMarkers = '/map-markers/meters',
  gatewayMapMarkers = '/map-markers/gateways',
  summaryMeters = '/summary/meters',
  gateways = '/gateways',
  users = '/users',
  authenticate = '/authenticate',
  logout = '/logout',
  measurements = '/measurements',
  organisations = '/organisations',
  dashboard = '/dashboards/current',
  userSelections = '/user/selections',
}
