export const BOOTSTRAP = 'BOOTSTRAP';

export const COLLECTION_REQUEST = 'COLLECTION_REQUEST';
export const COLLECTION_SUCCESS = 'COLLECTION_SUCCESS';
export const COLLECTION_FAILURE = 'COLLECTION_FAILURE';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';

export const DATA_ANALYSIS_REQUEST = 'DATA_ANALYSIS_REQUEST';
export const DATA_ANALYSIS_SUCCESS = 'DATA_ANALYSIS_SUCCESS';
export const DATA_ANALYSIS_FAILURE = 'DATA_ANALYSIS_FAILURE';

export const VALIDATION_REQUEST = 'VALIDATION_REQUEST';
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';
export const VALIDATION_FAILURE = 'VALIDATION_FAILURE';
