spring:
  application:
    name: MVP integration
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpH2Dialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 300

ehcache:
  heap-entries: 1000
  idle-time: 60

liquibase:
  enabled: false

mvp:
  url: http://localhost:8080
  consumers:
    rabbit:
      queueName: MVP
      responseRoutingKey: mvp.to.metering
  superadmin:
    email: mvpadmin@elvaco.se
    password: changeme

geo-service:
  url: http://localhost:8081
