spring:
  application:
    name: MVP integration
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpH2Dialect

liquibase:
  enabled: false
