spring:
  application:
    name: MVP integration
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpH2Dialect
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 30

liquibase:
  enabled: false
