server:
  port: 8080

spring:
  application:
    name: MVP
  datasource:
    url: jdbc:postgresql://localhost:5432/mvp
    username: mvp
    password: mvp
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpPostgreSqlDialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 30

ehcache:
  heap-entries: 1000
  idle-time: 60

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog.json
