server:
  port: 80

spring:
  application:
    name: MVP
  datasource:
    url: jdbc:postgresql://postgresql:5432/mvp
    username: mvp
    password: mvp
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.dialect.MvpPostgreSqlDialect
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace

zuul:
  routes:
    gateways:
      path: /v1/api/gateways/**
      url: http://localhost:4000/v1/api/gateways/
    meters:
      path: /v1/api/meters/**
      url: http://localhost:4000/v1/api/meters/
    selections:
      path: /v1/api/selections/**
      url: http://localhost:4000/v1/api/selections/
    dashboards:
      path: /v1/api/dashboards/**
      url: http://localhost:4000/v1/api/dashboards/

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog.json
