server:
  port: 8080

spring:
  application:
    name: MVP
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.dialect.MvpH2Dialect

zuul:
  routes:
    gateways:
      path: /v1/api/gateways/**
      url: http://localhost:4000/v1/api/gateways/
    meters:
      path: /v1/api/meters/**
      url: http://localhost:4000/v1/api/meters/
    selections:
      path: /v1/api/selections/**
      url: http://localhost:4000/v1/api/selections/
    dashboards:
      path: /v1/api/dashboards/**
      url: http://localhost:4000/v1/api/dashboards/

liquibase:
  enabled: false
