server:
  port: 80

spring:
  application:
    name: MVP
  datasource:
    url: jdbc:postgresql://postgresql:5432/mvp
    username: appuser
    password: 'RWZ8tKUzDdbncg2J'
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpPostgreSqlDialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 30

ehcache:
  heap-entries: 1000
  idle-time: 60

zuul:
  routes:
    selections:
      path: /v1/api/selections/**
      url: http://localhost:4000/v1/api/selections/
    dashboards:
      path: /v1/api/dashboards/**
      url: http://localhost:4000/v1/api/dashboards/

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog.json
  # super user credentials
  user: mvp
  password: mvp
  parameters:
    application_database: mvp
    application_user: appuser
    application_password: 'RWZ8tKUzDdbncg2J'
  # Not specifying this causes liquibase's autoconfiguration
  #  to use the datasource configured for JPA (with the corresponding user)
  url: jdbc:postgresql://localhost:5432/mvp
