server:
  port: 8080

spring:
  application:
    name: MVP
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpH2Dialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 30
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
ehcache:
  heap-entries: 1000
  idle-time: 20

zuul:
  routes:
    dashboards:
      path: /v1/api/dashboards/**
      url: http://localhost:4000/v1/api/dashboards/

liquibase:
  enabled: false

mvp:
  consumers:
    rabbit:
      queueName: MVP
