spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mvp
    driverClassName: org.postgresql.Driver
    username: appuser
    password: 'RWZ8tKUzDdbncg2J'
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpPostgreSqlDialect
  liquibase:
    user: mvp
    password: mvp
    # Not specifying this causes liquibase's autoconfiguration to use the Spring datasource, which
    # prevents us from overriding the user/password
    url: jdbc:postgresql://localhost:5432/mvp

jooq:
  sql-dialect: 'POSTGRES'
