server:
  port: 80

spring:
  application:
    name: MVP
  datasource:
    url: jdbc:postgresql://postgresql:5432/mvp
    driverClassName: org.postgresql.Driver
    username: appuser
    password: 'RWZ8tKUzDdbncg2J'
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpPostgreSqlDialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 300
      hibernate.integration.envers.enabled: true
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      org.hibernate.envers.audit_strategy_validity_store_revend_timestamp: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.default_schema: evoaudit
ehcache:
  heap-entries: 1000
  idle-time: 60

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog.xml
  # super user credentials
  user: mvp
  password: mvp
  parameters:
    application_database: mvp
    application_user: appuser
    application_password: 'RWZ8tKUzDdbncg2J'
  # Not specifying this causes liquibase's autoconfiguration
  #  to use the datasource configured for JPA (with the corresponding user)
  url: jdbc:postgresql://localhost:5432/mvp

mvp:
  url: http://localhost:8080

geo-service:
  url: http://localhost:8081
