server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  application:
    name: MVP
  profiles:
    active: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/mvp
    driverClassName: org.postgresql.Driver
    username: appuser
    password: 'RWZ8tKUzDdbncg2J'
    initialization-mode: never
  jpa:
    properties:
      hibernate.ddl-auto: validate
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpPostgreSqlDialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: false
      hibernate.type: trace
      hibernate.jdbc.batch_size: 300
      #mute wall-of-text feature test exceptions,
      # see https://github.com/spring-projects/spring-boot/issues/12007
      # and https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.integration.envers.enabled: true
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      org.hibernate.envers.audit_strategy_validity_store_revend_timestamp: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.default_schema: evoaudit
      org.hibernate.envers.allow_identifier_reuse: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog.xml
    # super user credentials
    user: mvp
    password: mvp
    # Not specifying this causes liquibase's autoconfiguration to use the Spring datasource, which
    # prevents us from overriding the user/password
    url: jdbc:postgresql://localhost:5432/mvp?tcpKeepAlive=true
    parameters:
      application_database: mvp
      application_user: appuser
      application_password: 'RWZ8tKUzDdbncg2J'
  jackson:
    serialization:
      # Backwards compat.
      # See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#jackson--json-support
      write-dates-as-timestamps: true

ehcache:
  token:
    heap-entries: 1000
    idle-time: 240
  metering:
    heap-entries: 1000
    idle-time: 10
  job-id:
    heap-entries: 20000
    idle-time: 10

mvp:
  url: http://localhost:8080
  consumers:
    rabbit:
      queueName: MVP
      responseExchange: ""
      responseRoutingKey: "mvp.to.metering"
      requeueRejected: false
      deadLetterExchange: "mvp.dead.letter"
      meteringFanoutExchange: "mvp.fanout"
      nbiotTopicExchange: "nbiot-test-ponte"
      prefetchCount: 250
      txSize: 1
  superadmin:
    email: "mvpadmin@elvaco.se"
    password: "changeme"
  root-organisation:
    name: "Elvaco"
    slug: "elvaco"


geo-service:
  url: http://localhost:8081

jooq:
  sql-dialect: 'POSTGRES'

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

zuul:
  routes:
    batches:
      path: /api/v1/batches/**
      url: http://localhost:8085/api/v1/batches/
    devices:
      path: /api/v1/devices/**
      url: http://localhost:8085/api/v1/devices/
