server:
  port: 8080

spring:
  application:
    name: MVP
  profiles:
    active: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
    initialize: false
  jpa:
    properties:
      hibernate.dialect: com.elvaco.mvp.database.dialect.MvpH2Dialect
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.jdbc.batch_size: 300
      hibernate.integration.envers.enabled: true
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
      org.hibernate.envers.audit_strategy_validity_store_revend_timestamp: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.default_schema: evoaudit
  rabbitmq:
    host: localhost
    username: guest
    password: guest

ehcache:
  heap-entries: 1000
  idle-time: 20

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog.xml
  # super user credentials
  parameters:
    application_database: mvp
    application_user: appuser
    application_password: 'RWZ8tKUzDdbncg2J'
  # Not specifying this causes liquibase's autoconfiguration
  #  to use the datasource configured for JPA (with the corresponding user)
  #  which is what we want for H2
  #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1


mvp:
  url: http://localhost:8080
  consumers:
    rabbit:
      queueName: MVP
      responseExchange: ""
      responseRoutingKey: "mvp.to.metering"
      requeueRejected: false
  superadmin:
    email: "mvpadmin@elvaco.se"
    password: "changeme"

geo-service:
  url: http://localhost:8081
