
insert into evoaudit.REVISION_ENTITY (TIMESTAMP) values( cast(EXTRACT(EPOCH FROM now()) as BIGINT) * 1000);

insert into evoaudit.GATEWAYS_METERS_AUD (REV, REVTYPE, LOGICAL_METER_ID , GATEWAY_ID )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, LOGICAL_METER_ID , GATEWAY_ID from GATEWAYS_METERS ;

insert into evoaudit.GATEWAY_AUD (REV, REVTYPE, ID, ORGANISATION_ID , ORGANISATION_ID_MOD , PRODUCT_MODEL , PRODUCT_MODEL_MOD , SERIAL ,SERIAL_MOD ,METERS_MOD )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID, ORGANISATION_ID, true, PRODUCT_MODEL, true, SERIAL, true, true from GATEWAY ;

insert into evoaudit.LOCATION_AUD  (REV, REVTYPE, LOGICAL_METER_ID , CITY  , CITY_MOD  , CONFIDENCE  , CONFIDENCE_MOD  , COUNTRY  ,COUNTRY_MOD  ,LATITUDE, LATITUDE_MOD  , LONGITUDE ,LONGITUDE_MOD ,STREET_ADDRESS ,STREET_ADDRESS_MOD   )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, LOGICAL_METER_ID , CITY , true, CONFIDENCE , true, COUNTRY , true, LATITUDE ,true, LONGITUDE,true,STREET_ADDRESS, true from LOCATION  ;

--TODO: METER_DEFINITION_TYPE   , METER_DEFINITION_MOD (is name correct of mod-table?)
insert into evoaudit.LOGICAL_METER_AUD   (REV, REVTYPE, ID  , CREATED   , CREATED_MOD   , EXTERNAL_ID   , EXTERNAL_ID_MOD   , ORGANISATION_ID   ,ORGANISATION_ID_MOD   ,GATEWAYS_MOD , METER_DEFINITION_TYPE   , METER_DEFINITION_MOD  ,PHYSICAL_METERS_MOD  ,LOCATION_MOD )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID  , CREATED  , true, EXTERNAL_ID  , true, ORGANISATION_ID  , true, true, METER_DEFINITION_TYPE ,true, true,true from LOGICAL_METER   ;

insert into evoaudit.METER_DEFINITION_AUD (REV, REVTYPE, TYPE, MEDIUM ,MEDIUM_MOD ,SYSTEM_OWNED ,SYSTEM_OWNED_MOD ,QUANTITIES_MOD)
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, TYPE, MEDIUM, true, SYSTEM_OWNED, true, true  from METER_DEFINITION;

insert into evoaudit.METER_DEFINITION_QUANTITIES_AUD (REV, REVTYPE, METER_DEFINITION_TYPE, QUANTITY_ID )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, METER_DEFINITION_TYPE  , QUANTITY_ID from METER_DEFINITION_QUANTITIES;

insert into evoaudit.MVP_SETTING_AUD     (REV, REVTYPE, ID, NAME, NAME_MOD , VALUE , VALUE_MOD  )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID   , NAME,true ,VALUE ,true   from MVP_SETTING ;

insert into evoaudit.MVP_USER_AUD      (REV, REVTYPE, ID, EMAIL , EMAIL_MOD  , LANGUAGE  , LANGUAGE_MOD,NAME ,NAME_MOD ,ORGANISATION_ID ,ORGANISATION_MOD ,ROLES_MOD    )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID   , EMAIL ,true ,LANGUAGE  ,true,NAME ,true,ORGANISATION_ID ,true,true   from MVP_USER  ;

insert into evoaudit.ORGANISATION_AUD(REV, REVTYPE, ID,EXTERNAL_ID, EXTERNAL_ID_MOD, NAME, NAME_MOD, SLUG,SLUG_MOD, USERS_MOD)
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID, EXTERNAL_ID, true, NAME, true, SLUG, true, true from ORGANISATION;

insert into evoaudit.PHYSICAL_METER_AUD  (REV, REVTYPE, ID,ADDRESS , ADDRESS_MOD , EXTERNAL_ID , EXTERNAL_ID_MOD , LOGICAL_METER_ID ,LOGICAL_METER_ID_MOD , MANUFACTURER ,MANUFACTURER_MOD,MEDIUM ,MEDIUM_MOD ,READ_INTERVAL_MINUTES ,READ_INTERVAL_MINUTES_MOD ,ORGANISATION_ID ,ORGANISATION_MOD )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID, ADDRESS , true , EXTERNAL_ID , true , LOGICAL_METER_ID ,true , MANUFACTURER ,true,MEDIUM ,true ,READ_INTERVAL_MINUTES ,true ,ORGANISATION_ID ,true  from PHYSICAL_METER ;

insert into evoaudit.QUANTITY_AUD (REV, REVTYPE, ID,NAME, NAME_MOD, SERIES_DISPLAY_MODE, SERIES_DISPLAY_MODE_MOD, UNIT, UNIT_MOD)
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID, NAME, true, SERIES_DISPLAY_MODE, true  , UNIT  ,true  from QUANTITY;

insert into evoaudit.ROLE_AUD (REV, REVTYPE, ROLE, USERS_MOD)
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ROLE, true from ROLE;

insert into evoaudit.USERS_ROLES_AUD  (REV, REVTYPE, USER_ID , ROLE_ID )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, USER_ID , ROLE_ID from USERS_ROLES ;

insert into evoaudit.USER_SELECTION_AUD   (REV, REVTYPE, ID  , NAME ,NAME_MOD ,ORGANISATION_ID ,ORGANISATION_ID_MOD ,OWNER_USER_ID ,OWNER_USER_ID_MOD ,SELECTION_PARAMETERS ,SELECTION_PARAMETERS_MOD  )
    select (select max(id) from evoaudit.REVISION_ENTITY), 0, ID  , NAME ,true ,ORGANISATION_ID ,true ,OWNER_USER_ID ,true ,SELECTION_PARAMETERS ,true from USER_SELECTION  ;
